### ISSUE TITLE
How to run a demo?

### ISSUE THREAD

**Issue by MHCP001-YUI** [YaoChengTang/DecNet#1]
Hello, thanks for sharing this great research.
I'm currently studying depth estimation - can you share a document or a code file with me for running a stereo demo?

**Comment by YaoChengTang** [comment]
We currently only provide the CUDA code of sparse matching and variance estimation. The demo code is coming soon.

**Comment by MHCP001-YUI** [comment]
> We currently only provide the CUDA code of sparse matching and variance estimation. The demo code is coming soon.

Thanks for your reply~

**Comment by MHCP001-YUI** [comment]
Continue to pay attention...... What is the speed for 1080p imagesize?
