### ISSUE TITLE
The link to the pre-trained model is invalid

### ISSUE THREAD

**Issue by weiyangdaren** [YaoChengTang/DecNet#2]
Thanks for your code. The link to the pre-trained model is invalid. Can you provide a new link?

**Comment by YaoChengTang** [comment]
Link: https://pan.baidu.com/s/1S8QWo-uyUzMIbNx4o9mBGQ
Extraction code: xthi

**Comment by drozzy** [comment]
Would it be possible to download these without installing the download client?
